/* 
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = CFBSharp.Client.SwaggerDateConverter;

namespace CFBSharp.Model
{
    /// <summary>
    /// TeamSeason
    /// </summary>
    [DataContract]
    public partial class TeamSeason :  IEquatable<TeamSeason>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamSeason" /> class.
        /// </summary>
        /// <param name="school">school.</param>
        /// <param name="year">year.</param>
        /// <param name="games">games.</param>
        /// <param name="wins">wins.</param>
        /// <param name="losses">losses.</param>
        /// <param name="ties">ties.</param>
        /// <param name="preseasonRank">Rank in the AP preseason poll.</param>
        /// <param name="postseasonRank">Final ranking in the AP poll.</param>
        public TeamSeason(string school = default(string), string year = default(string), int? games = default(int?), int? wins = default(int?), int? losses = default(int?), int? ties = default(int?), int? preseasonRank = default(int?), int? postseasonRank = default(int?))
        {
            this.School = school;
            this.Year = year;
            this.Games = games;
            this.Wins = wins;
            this.Losses = losses;
            this.Ties = ties;
            this.PreseasonRank = preseasonRank;
            this.PostseasonRank = postseasonRank;
        }
        
        /// <summary>
        /// Gets or Sets School
        /// </summary>
        [DataMember(Name="school", EmitDefaultValue=false)]
        public string School { get; set; }

        /// <summary>
        /// Gets or Sets Year
        /// </summary>
        [DataMember(Name="year", EmitDefaultValue=false)]
        public string Year { get; set; }

        /// <summary>
        /// Gets or Sets Games
        /// </summary>
        [DataMember(Name="games", EmitDefaultValue=false)]
        public int? Games { get; set; }

        /// <summary>
        /// Gets or Sets Wins
        /// </summary>
        [DataMember(Name="wins", EmitDefaultValue=false)]
        public int? Wins { get; set; }

        /// <summary>
        /// Gets or Sets Losses
        /// </summary>
        [DataMember(Name="losses", EmitDefaultValue=false)]
        public int? Losses { get; set; }

        /// <summary>
        /// Gets or Sets Ties
        /// </summary>
        [DataMember(Name="ties", EmitDefaultValue=false)]
        public int? Ties { get; set; }

        /// <summary>
        /// Rank in the AP preseason poll
        /// </summary>
        /// <value>Rank in the AP preseason poll</value>
        [DataMember(Name="preseason_rank", EmitDefaultValue=false)]
        public int? PreseasonRank { get; set; }

        /// <summary>
        /// Final ranking in the AP poll
        /// </summary>
        /// <value>Final ranking in the AP poll</value>
        [DataMember(Name="postseason_rank", EmitDefaultValue=false)]
        public int? PostseasonRank { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TeamSeason {\n");
            sb.Append("  School: ").Append(School).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  Games: ").Append(Games).Append("\n");
            sb.Append("  Wins: ").Append(Wins).Append("\n");
            sb.Append("  Losses: ").Append(Losses).Append("\n");
            sb.Append("  Ties: ").Append(Ties).Append("\n");
            sb.Append("  PreseasonRank: ").Append(PreseasonRank).Append("\n");
            sb.Append("  PostseasonRank: ").Append(PostseasonRank).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TeamSeason);
        }

        /// <summary>
        /// Returns true if TeamSeason instances are equal
        /// </summary>
        /// <param name="input">Instance of TeamSeason to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TeamSeason input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.School == input.School ||
                    (this.School != null &&
                    this.School.Equals(input.School))
                ) && 
                (
                    this.Year == input.Year ||
                    (this.Year != null &&
                    this.Year.Equals(input.Year))
                ) && 
                (
                    this.Games == input.Games ||
                    (this.Games != null &&
                    this.Games.Equals(input.Games))
                ) && 
                (
                    this.Wins == input.Wins ||
                    (this.Wins != null &&
                    this.Wins.Equals(input.Wins))
                ) && 
                (
                    this.Losses == input.Losses ||
                    (this.Losses != null &&
                    this.Losses.Equals(input.Losses))
                ) && 
                (
                    this.Ties == input.Ties ||
                    (this.Ties != null &&
                    this.Ties.Equals(input.Ties))
                ) && 
                (
                    this.PreseasonRank == input.PreseasonRank ||
                    (this.PreseasonRank != null &&
                    this.PreseasonRank.Equals(input.PreseasonRank))
                ) && 
                (
                    this.PostseasonRank == input.PostseasonRank ||
                    (this.PostseasonRank != null &&
                    this.PostseasonRank.Equals(input.PostseasonRank))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.School != null)
                    hashCode = hashCode * 59 + this.School.GetHashCode();
                if (this.Year != null)
                    hashCode = hashCode * 59 + this.Year.GetHashCode();
                if (this.Games != null)
                    hashCode = hashCode * 59 + this.Games.GetHashCode();
                if (this.Wins != null)
                    hashCode = hashCode * 59 + this.Wins.GetHashCode();
                if (this.Losses != null)
                    hashCode = hashCode * 59 + this.Losses.GetHashCode();
                if (this.Ties != null)
                    hashCode = hashCode * 59 + this.Ties.GetHashCode();
                if (this.PreseasonRank != null)
                    hashCode = hashCode * 59 + this.PreseasonRank.GetHashCode();
                if (this.PostseasonRank != null)
                    hashCode = hashCode * 59 + this.PostseasonRank.GetHashCode();
                return hashCode;
            }
        }
    }

}
